name: "Scenarigo Run"
description: "Install the scenarigo CLI and execute `scenarigo run` in a target directory"
inputs:
  scenarigo-version:
    description: "Version of scenarigo CLI to install (e.g. v0.15.0, latest)"
    required: false
    default: "latest"
  working-directory:
    description: "Directory containing scenarigo configuration and scenarios"
    required: false
    default: "."
  run-args:
    description: "Additional arguments passed to `scenarigo run`"
    required: false
    default: ""
  build-plugins:
    description: "Whether to build plugins before running scenarios"
    required: false
    default: "true"
  build-args:
    description: "Additional arguments passed to `scenarigo plugin build` when building plugins"
    required: false
    default: ""
  list-args:
    description: "Additional arguments passed to `scenarigo plugin list` when building plugins"
    required: false
    default: ""
  report-json:
    description: "File path for scenarigo JSON report (adds `--report-json` when set)"
    required: false
    default: ""
  report-junit:
    description: "File path for scenarigo JUnit report (adds `--report-junit` when set)"
    required: false
    default: ""
outputs:
  plugin-paths:
    description: "Newline-separated plugin paths built/listed when plugin build runs"
    value: ${{ steps.set-plugin-paths.outputs.plugin-paths }}
runs:
  using: "composite"
  steps:
  - name: Install dependencies
    uses: ./install
    with:
      scenarigo-version: ${{ inputs.scenarigo-version }}

  - name: Build plugins
    id: build-plugins
    if: ${{ inputs.build-plugins == 'true' }}
    uses: ./build-plugin
    with:
      scenarigo-version: ${{ inputs.scenarigo-version }}
      working-directory: ${{ inputs.working-directory }}
      build-args: ${{ inputs.build-args }}
      list-args: ${{ inputs.list-args }}

  - name: Set plugin paths output
    id: set-plugin-paths
    shell: bash
    env:
      BUILT_PATHS: ${{ steps.build-plugins.outputs.paths }}
    run: |
      set -euo pipefail
      if [ -n "${BUILT_PATHS}" ]; then
        printf "plugin-paths<<EOF\n%s\nEOF\n" "${BUILT_PATHS}" >> "$GITHUB_OUTPUT"
      else
        echo "plugin-paths=" >> "$GITHUB_OUTPUT"
      fi

  - name: Run scenarigo
    id: run-scenarigo
    shell: bash
    env:
      WORKDIR: ${{ inputs.working-directory }}
      RUN_ARGS: ${{ inputs.run-args }}
      REPORT_JSON_PATH: ${{ inputs.report-json }}
      REPORT_JUNIT_PATH: ${{ inputs.report-junit }}
    run: |
      set -euo pipefail
      REPORT_JUNIT_ABS=""
      # Default to colored output, but disable when JUnit is requested to avoid ANSI codes in XML.
      SCENARIGO_COLOR=true
      NO_COLOR=""
      # Build args array to avoid breaking on spaces and to append optional reports.
      ARGS=()
      if [ -n "${RUN_ARGS}" ]; then
        # Users can pass multiple flags via run-args; allow word splitting intentionally.
        # shellcheck disable=SC2206
        ARGS+=(${RUN_ARGS})
      fi
      if [ -n "${REPORT_JSON_PATH}" ]; then
        ARGS+=(--report-json "${REPORT_JSON_PATH}")
      fi
      if [ -n "${REPORT_JUNIT_PATH}" ]; then
        case "${REPORT_JUNIT_PATH}" in
          /*) REPORT_JUNIT_ABS="${REPORT_JUNIT_PATH}" ;;
          *) REPORT_JUNIT_ABS="$(cd "${WORKDIR}" && pwd)/${REPORT_JUNIT_PATH}" ;;
        esac
        ARGS+=(--report-junit "${REPORT_JUNIT_ABS}")
        printf "report-junit-abs=%s\n" "${REPORT_JUNIT_ABS}" >> "$GITHUB_OUTPUT"
        SCENARIGO_COLOR=""
        NO_COLOR=true
      fi
      echo "Entering directory: ${WORKDIR}"
      cd "${WORKDIR}"
      if [ -n "${SCENARIGO_COLOR}" ]; then
        export SCENARIGO_COLOR
      fi
      if [ -n "${NO_COLOR}" ]; then
        export NO_COLOR
      fi
      echo "Running: scenarigo run ${ARGS[*]}"
      scenarigo run "${ARGS[@]}"
  - name: Publish test report
    if: ${{ !cancelled() && steps.run-scenarigo.outputs.report-junit-abs != '' }}
    uses: dorny/test-reporter@v1
    with:
      name: scenarigo tests
      path: ${{ steps.run-scenarigo.outputs.report-junit-abs }}
      reporter: java-junit
      fail-on-error: false
branding:
  icon: "play-circle"
  color: "green"
